# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
    - main

  # executar o job manualmente
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
        
    # instalacao das dependências
    - run: npm install
    
    # execucao dos testes
    - run: npx cypress run
        
    # upload dos vídeos gerados
    - name: Upload videos
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: videos
        path: cypress/videos
